
DROP TABLE IF EXISTS ORDER_PROMO;
DROP TABLE IF EXISTS ORDER_TABLE;
DROP TABLE IF EXISTS ORDER_SUMMARY;
DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price DECIMAL DEFAULT 0,
  quantity INT DEFAULT 0
);

CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

CREATE TABLE ORDER_SUMMARY (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  order_time TIMESTAMP NOT NULL,
  original_cost DECIMAL DEFAULT 0,
  final_discount DECIMAL DEFAULT 0,
  final_cost DECIMAL DEFAULT 0,
  FOREIGN KEY (customer_id) references CUSTOMER(id)
);
  
CREATE TABLE ORDER_TABLE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  order_summary_id INT NOT NULL,
  quantity INT DEFAULT 0,
  FOREIGN KEY (product_id) references PRODUCT(id),
  FOREIGN KEY (order_summary_id) references ORDER_SUMMARY(id)
);
  
CREATE TABLE ORDER_PROMO (
  id INT AUTO_INCREMENT PRIMARY KEY,
  promo_name VARCHAR(250) NOT NULL,
  order_summary_id INT NOT NULL,
  quantity INT DEFAULT 0,
  discount DECIMAL DEFAULT 0,
  FOREIGN KEY (order_summary_id) references ORDER_SUMMARY(id)
);