DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  price DECIMAL DEFAULT 0
);

DROP TABLE IF EXISTS CUSTOMER;

CREATE TABLE CUSTOMER (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS ORDER_SUMMARY;

CREATE TABLE ORDER_SUMMARY (
  id INT AUTO_INCREMENT PRIMARY KEY,
  customer_id INT NOT NULL,
  order_time TIMESTAMP NOT NULL,
  original_cost DECIMAL DEFAULT 0,
  final_discount DECIMAL DEFAULT 0,
  final_cost DECIMAL DEFAULT 0,
  FOREIGN KEY (customer_id) references CUSTOMER(id)
);

DROP TABLE IF EXISTS ORDER_TABLE;
  
CREATE TABLE ORDER_TABLE (
  id INT AUTO_INCREMENT PRIMARY KEY,
  product_id INT NOT NULL,
  order_summary_id INT NOT NULL,
  quantity INT DEFAULT 0,
  FOREIGN KEY (product_id) references PRODUCT(id),
  FOREIGN KEY (order_summary_id) references ORDER_SUMMARY(id)
);